#config_version=5
##! show: attract_display_loop
#! - duration: .1
#!   events: ok_super
##! mode: attract

show_player:
  mode_attract_started: attract_display_loop
  mode_attract_started.1: attract_light_show
##! test
#! mock_event ok_super
#! advance_time_and_run .1
#! assert_event_called ok_super