#config_version=5

displays:
  window:
    width: 800
    height: 600
##! test
#! advance_time_and_run .1

slides:
  welcome_slide:
    widgets:
      - type: text
        text: PINBALL!
#! slide_player:
#!   show_slide_event: welcome_slide
##! test
#! post show_slide_event
#! advance_time_and_run .1
#! assert_slide_on_top welcome_slide
#! assert_text_on_top_slide PINBALL!

slide_player:
  init_done: welcome_slide
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50
  mode_attract_started: welcome_slide