#config_version=5

#hardware:
  #platform: opp
  #driverboards: gen2

#opp:
  #Use the USB ports defined by your OS for the two STM32 boards
  #ports: /dev/ttyACM0, /dev/ttyACM1
  #USING SERIAL NUMBERS INSTEAD OF CHAINS
  #  Board 0 has serial number 0, Board 1 has serial number 1.
  #  This is convenient if your OS tends to reassign the serial port.
  #  MPF will automatically address the correct board even if the ports
  #     are swapped.

  #For multiple CobraPin boards in a game, you will either have to give 
  #  the STM32 boards on the second CobraPin board new serial numbers 
  #  (10 and 11 are suggested for the 2nd board since 2 is used by the 
  #  CobraPin Xpansion Board) 
  #  <OR> Use the chains section to assign a port to a board number. 
  #  Mixing these up could cause blown FETs, coils, and fuses. Proceed 
  #  with caution. Test without coil power and use the yellow coil LEDs 
  #  for feedback.
  #chains:
     #0: /dev/ttyACM0
     #1: /dev/ttyACM1

psus:
  default:
    #Gives the capacitors extra time to recharge after firing a coil
    #  and eases the load on the power supply. Doesn't affect autofire
    #  devices like flippers, pops, slings.
    release_wait_ms: 50  

config:
  - coils.yaml
  - switches.yaml
  - devices.yaml
  - displays.yaml
  - keyboard.yaml
  - lights.yaml

modes:
  - base
  - target_mb
  - lastchance
  - vacation
  - skillshot


machine:
  balls_installed: 4
virtual_platform_start_active_switches: s_trough_1

mpf:
  report_crashes: never


  
